// <auto-generated />
namespace PropertyManager.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new80 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new80));
        
        string IMigrationMetadata.Id
        {
            get { return "201602190522154_new80"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
